#!/usr/bin/env php
<?php

// application.php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/boot/bootstrap.php';
require __DIR__.'/boot/register-commands.php';

use Symfony\Component\Console\Application;

$application = new Application();
set_application_info($application);

// ... auto register commands
register_commands($application);

try {
    $application->run();
} catch (Exception $e) {
    dump($e->getMessage());
}
